source 'https://rubygems.org'
gem 'ostruct'
gem 'logger'
gem 'csv'
gem 'base64'
gem 'bigdecimal'
group :jekyll_plugins do
    gem 'jekyll'
    gem 'jekyll-email-protect'
    gem 'jekyll-feed'
    gem 'jekyll-github-metadata'
    gem 'jekyll-paginate-v2'
    gem 'jekyll-scholar'
    gem 'jekyll-twitter-plugin'
    gem 'jekyll-sitemap'
    gem 'jemoji'
    gem 'unicode_utils'
    gem 'webrick'
end
